### ISSUE TITLE
Failed to launch the browser process! - Debian Buster

### ISSUE THREAD

**Issue by micha-net** [kennethaasan/aws-azure-login#213]
I run the latest docker image (docker run -it -v ~/.aws:/root/.aws -t aal sportradar/aws-azure-login --mode=debug) and get the error message bellow since one week (worked before). Same with --mode=gui

I am not sure which details help, so here are the host kernel version and the docker version. Linux itself runs as a VM.
Linux kernel: 4.19.0-18-amd64
Docker version 20.10.10, build b485636

`Error: Failed to launch the browser process!
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
[16:16:1107/120831.707576:ERROR:browser_main_loop.cc(1425)] Unable to open X display.
[1107/120831.711154:ERROR:nacl_helper_linux.cc(307)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:194:20)
    at ChildProcess.<anonymous> (/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:79)
    at ChildProcess.emit (events.js:387:35)
    at ChildProcess.emit (domain.js:470:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
`

**Comment by boiko-danylo** [comment]
I have the same issue on Fedora 34

**Comment by micha-net** [comment]
This issue is related to this one: https://github.com/sportradar/aws-azure-login/issues/210

After changing my default MFA method to the app it worked again for me.
The browser crash should not happen anyway though imho. For several of my colleagues the browser did not crash.
