### ISSUE TITLE
Protocol error/socket hang up when trying to login

### ISSUE THREAD

**Issue by trygveaa** [kennethaasan/aws-azure-login#215]
I've installed and configured aws-azure-login, but when trying to run it (without any options) I get:

```
Logging in with profile 'default'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
Error: Protocol error (Target.activateTarget): Session closed. Most likely the page has been closed.
    at CDPSession.send (/home/trygve/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:35)
    at Page._screenshotTask (/home/trygve/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1927:28)
    at /home/trygve/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1924:62
```

If I run it with `--mode gui` it prints an `ErrorEvent` with the message `socket hang up`.

<details>
  <summary>Full output</summary>

```
Logging in with profile 'default'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'ws://127.0.0.1:41805/devtools/browser/ff657660-58f3-4c7f-bb5e-10f7fa7757c4',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'socket hang up',
  error: Error: socket hang up
      at connResetException (internal/errors.js:639:14)
      at Socket.socketOnEnd (_http_client.js:499:23)
      at Socket.emit (events.js:412:35)
      at Socket.emit (domain.js:475:12)
      at endReadableNT (internal/streams/readable.js:1334:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    code: 'ECONNRESET'
  }
}
```
</details>

I'm running an up to date Arch Linux with nodejs-lts-fermium (so node v14.18.1, but I also tried node v16.11.1 and get the same) and I have configured `kernel.unprivileged_userns_clone=1`.

**Comment by trygveaa** [comment]
I see that I get this issue with puppeteer outside aws-azure-login too, so I'll close this. It seems to be this issue: https://github.com/puppeteer/puppeteer/issues/7455

**Comment by luismramirezr** [comment]
hey @trygveaa were you able to solve this?

**Comment by trygveaa** [comment]
@luismramirezr: Yes, as mentioned [here](https://github.com/puppeteer/puppeteer/issues/7455#issuecomment-1026783555) it works with puppeteer >= 12.0.0.
