### ISSUE TITLE
Unable to connect the AWS DB using the Azure Single sign on

### ISSUE THREAD

**Issue by Raja4500** [kennethaasan/aws-azure-login#243]
The following error will be prompted while we connect to AWS DB. 

PS C:\Windows\system32> aws-azure-login --profile XXXX --mode=gui
Logging in with profile 'XXXXX'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:700:9)
    at BrowserRunner.start (C:\Users\XXXXXX.AzureAD\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:80:34)
    at ChromeLauncher.launch (C:\Users\XXXXX.AzureAD\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:94:16)
    at async Object._performLoginAsync (C:\Users\XXXXXX.AzureAD\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:461:23)
    at async Object.loginAsync (C:\Users\XXXXXX.AzureAD\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:324:30) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}

**Comment by lukesalter71** [comment]
Hi, did you get this issue resolved? I am currently encountering the same issue.
