### ISSUE TITLE
TypeError: this.breakLines(...).flat is not a function

### ISSUE THREAD

**Issue by fuellbie** [kennethaasan/aws-azure-login#287]
Running Ubuntu. Installed `aws-azure-login` via npm.

I am getting following error:
```
$ aws-azure-login  --configure
Configuring profile 'default'
(node:116985) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
TypeError: this.breakLines(...).flat is not a function
    at ScreenManager.forceLineReturn (/usr/local/lib/node_modules/aws-azure-login/node_modules/inquirer/lib/utils/screen-manager.js:172:56)
    at ScreenManager.render (/usr/local/lib/node_modules/aws-azure-login/node_modules/inquirer/lib/utils/screen-manager.js:81:20)
    at InputPrompt.render (/usr/local/lib/node_modules/aws-azure-login/node_modules/inquirer/lib/prompts/input.js:67:17)
    at InputPrompt._run (/usr/local/lib/node_modules/aws-azure-login/node_modules/inquirer/lib/prompts/input.js:34:10)
    at Promise (/usr/local/lib/node_modules/aws-azure-login/node_modules/inquirer/lib/prompts/base.js:61:12)
    at new Promise (<anonymous>)
    at InputPrompt.run (/usr/local/lib/node_modules/aws-azure-login/node_modules/inquirer/lib/prompts/base.js:60:12)
    at defer (/usr/local/lib/node_modules/aws-azure-login/node_modules/inquirer/lib/ui/prompt.js:105:30)
    at Observable._subscribe (/usr/local/lib/node_modules/aws-azure-login/node_modules/rxjs/dist/cjs/internal/observable/defer.js:8:31)
    at Observable._trySubscribe (/usr/local/lib/node_modules/aws-azure-login/node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
    at /usr/local/lib/node_modules/aws-azure-login/node_modules/rxjs/dist/cjs/internal/Observable.js:35:31
    at Object.errorContext (/usr/local/lib/node_modules/aws-azure-login/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
    at Observable.subscribe (/usr/local/lib/node_modules/aws-azure-login/node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)
    at doInnerSub (/usr/local/lib/node_modules/aws-azure-login/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:22:56)
    at outerNext (/usr/local/lib/node_modules/aws-azure-login/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:17:70)
    at OperatorSubscriber._this._next (/usr/local/lib/node_modules/aws-azure-login/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
```
I am aware of https://github.com/aws-azure-login/aws-azure-login/issues/268, but I am not sure if the `TypeError` is related to the `NOTE`.

**Comment by fuellbie** [comment]
My NodeJS version was too old. Updated to newer version fixed it.
