### ISSUE TITLE
TimeoutError: waiting for selector `input[name="loginfmt"]

### ISSUE THREAD

**Issue by jpChan015** [kennethaasan/aws-azure-login#310]
`TimeoutError: waiting for selector `input[name="loginfmt"]` failed: timeout 60000ms exceeded
    at new WaitTask (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528:34)
    at DOMWorld.waitForSelectorInPage (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:432:26)
    at Object.internalHandler.waitFor (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:323:29)
    at Frame.waitForSelector (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:942:51)
    at Page.waitForSelector (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2370:33)
    at Object.handler (/usr/local/lib/node_modules/aws-azure-login/lib/login.js:70:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object._performLoginAsync (/usr/local/lib/node_modules/aws-azure-login/lib/login.js:605:29)
    at async Object.loginAsync (/usr/local/lib/node_modules/aws-azure-login/lib/login.js:377:30)`

**Comment by jacobhpAZ** [comment]
Hi,
Did you get anywhere with solving this?

**Comment by phergoualch** [comment]
I get the same error and looking for a solution

**Comment by samtarplee** [comment]
I'm not sure why it worked, but running it with the `--mode gui` flag, logging in, and then going back to running it without that flag resolved this

**Comment by akshithnair** [comment]
@samtarplee lifesaver, thanks !
