### ISSUE TITLE
aws-azure-login -m gui crashes with error in Apple Macbook M3 Pro

### ISSUE THREAD

**Issue by nagarjunr** [kennethaasan/aws-azure-login#325]
I encountered the following error after I entered my sso credentials in the chromium window.

Error:
~ % aws-azure-login -m gui
Logging in with profile 'default'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
Please complete the login in the opened window
Assuming role arn:aws:iam::MY-AWS-ACCOUNT-NUMBER:role/RB-IDP-Federated-Administrator in region ap-south-1...
TypeError: (0 , proxy_agent_1.default) is not a function
    at Object._assumeRoleAsync (/opt/homebrew/lib/node_modules/aws-azure-login/lib/login.js:773:59)
    at Object.loginAsync (/opt/homebrew/lib/node_modules/aws-azure-login/lib/login.js:381:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Installation:
brew install node
brew install chromium --no-quarantine
npm install -g aws-azure-login

Environment Variables:
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH=`which chromium`

Versions:
node : v22.0.0
Chromium : Version 126.0.6443.0 (Developer Build) (arm64)

Platform: 
MacBook Pro 14-inch, Nov 2023
Chipset: Apple M3 Pro

**Comment by naresh-avula** [comment]
was this fixed?
