### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'load')

### ISSUE THREAD

**Issue by Pratikshakilledar** [kennethaasan/aws-azure-login#342]
Hi,
I have configured aws-azure profiles on windows and while login to aws via cmd I am detting below errors:

TypeError: Cannot read properties of undefined (reading 'load')
    at Object._parseRolesFromSamlResponse (C:\Users\pratiksha.shintre\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:663:40)
    at Object.loginAsync (C:\Users\pratiksha.shintre\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:379:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

I have tried all solutions available but still its not working.

**Comment by sanjayv-inspira** [comment]
I'm seeing the same error for all node versions 18 and up.

**Comment by vsanjay85** [comment]
I'm seeing the same error for all node versions 18 and up.

Edit: Found a workaround here: https://github.com/aws-azure-login/aws-azure-login/issues/339#issuecomment-2290950342

**Comment by Garethp** [comment]
Try moving over to the [`aws-azure-auth`](https://www.npmjs.com/package/aws-azure-auth) package as a replacement
